Repository ytvnr/gif-of-the-day, pull requests merged in 2019-12, with the labels that each got.

#11 feat: display teams collection in Teams.vue 🤼‍
  firestore.rules
  front/.gitignore
  front/package-lock.json
  front/package.json
  front/src/App.vue
  front/src/firebaseConfig.template.json
  front/src/main.js
  front/src/router/index.js
  front/src/views/About.vue
  front/src/views/Home.vue
  front/src/views/Teams.vue
  functions/tslint.json
Labels: enhancement

#17 feat: add authentication and display profile picture 🗝
  front/package-lock.json
  front/src/assets/logo.png
  front/src/components/NavBar.vue
Labels: enhancement

#20 chore: init github action on pr to deploy 🚀
  .github/workflows/on-push.yml
Labels: Technical task 👨🏻‍🔧

#19 doc: update README.MD with ci secret generation 📄
  README.md
Labels: Documentation 📒

#26 feat: join a team and persist it
  firestore.rules
  front/src/App.vue
  front/src/components/NavBar.vue
  front/src/components/TeamCard.vue
  front/src/main.js
  front/src/services/user.service.js
  front/src/views/Teams.vue
Labels: Feature 🎉
