Repository ytvnr/gif-of-the-day, pull requests merged in 2020-03, with the labels that each got.

#66 feat: init login / register with email / password 📮
  front/package-lock.json
  front/package.json
  front/src/App.vue
  front/src/components/Drawer.vue
  front/src/main.js
  front/src/router/index.js
  front/src/store/index.js
  front/src/views/Login.vue
  front/src/views/Register.vue
Labels: Feature 🎉, Work in progress 🚧

#67 feat: register only if mail domain is authorized
  firestore.rules
  front/package-lock.json
  front/src/store/index.js
Labels: Feature 🎉

#48 feat: build first version of extension 🥳
  .prettierrc
  extension.zip
  extension/.gitignore
  extension/icon.png
  extension/icons/128.png
  extension/icons/152.png
  extension/icons/16.png
  extension/icons/32.png
  extension/icons/48.png
  extension/icons/favicon.ico
  extension/index.html
  extension/logo.png
  extension/manifest.json
  extension/package.json
  extension/release.zip
  front/.env
  front/.env.local
  front/babel.config.js
  front/package.json
  front/public/extension/index.js
  front/public/extension/manifest.json
  front/public/img/github.png
  front/public/img/google.png
  front/public/img/icon.png
  front/public/index.html
  front/src/firebase/init.js
  front/src/store/index.js
  front/src/views/About.vue
  front/src/views/Login.vue
  front/vue.config.js
  sources/app-preview-1.jpg
Labels: Bug 🐜, Extension 🥕, Technical task 👨🏻‍🔧

#68 feat: display home page content
  front/src/store/index.js
  front/src/views/Home.vue
  front/src/views/Logout.vue
Labels: Feature 🎉

#71 fix: keep state when refreshing using sessionStorage
  front/package-lock.json
  front/package.json
  front/src/store/index.js
  front/src/views/Home.vue
Labels: Bug 🐜

#72 chore: build before merge
  .github/workflows/staging-pr.yml
Labels: Technical task 👨🏻‍🔧

#73 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation 📒

#69 Display gif themes by teams
  firestore.rules
  front/package-lock.json
  front/src/components/TeamCard.vue
  front/src/store/index.js
  front/src/views/Home.vue
  front/src/views/Schedule.vue
  front/src/views/Teams.vue
Labels: Feature 🎉, Work in progress 🚧

#77 feat: use tiles for home page 💄👀
  front/package-lock.json
  front/package.json
  front/src/views/Home.vue
Labels: Feature 🎉

#80 feat: edit theme for a day, save it and display it in home page 💄💪
  front/src/services/teams.service.js
  front/src/views/Home.vue
  front/src/views/Schedule.vue
Labels: Feature 🎉

#79 feat: display gifs list 🥳
  front/.env
  front/.env.local
  front/package-lock.json
  front/package.json
  front/src/components/Drawer.vue
  front/src/services/giphy.service.js
  front/src/views/Gifs.vue
Labels: Feature 🎉

#81 fix: display team name if we have team 🐛
  front/src/views/Home.vue
Labels: Bug 🐜

#82 feat: display a random gif matching theme of the day on home page 💅
  front/package-lock.json
  front/src/services/giphy.service.js
  front/src/views/Home.vue
Labels: Feature 🎉

#84 feat: theme of the day as default value in search input 💪
  front/src/services/teams.service.js
  front/src/views/Gifs.vue
Labels: Feature 🎉

#85 Some fix and features
  front/src/firebase/init.js
  front/src/router/index.js
  front/src/services/teams.service.js
  front/src/views/Home.vue
  front/src/views/Schedule.vue
Labels: Bug 🐜, Feature 🎉

#87 fix: call assignedTeamId computed to init it
  front/src/views/Home.vue
Labels: Bug 🐜

#86 feat: can submit with enter when logging in 🤡
  front/src/views/Login.vue
Labels: Feature 🎉

#88 feat: init first version of FAQ 🧾
  front/src/components/Drawer.vue
  front/src/router/index.js
  front/src/views/Faq.vue
Labels: Extension 🥕, Feature 🎉
