Repository ytvnr/gif-of-the-day, pull requests merged in 2020-02, with the labels that each got.

#41 feat: use vuetify editable table
  front/package-lock.json
  front/src/views/Gifs.vue
Labels: Feature 🎉

#45 docs: update readme badges
  README.md
Labels: Documentation 📒

#52 feat: rework on team card
  front/src/components/TeamCard.vue
  front/src/views/Teams.vue
Labels: Feature 🎉

#55 feat: use store for assignedTeamId
  front/src/components/TeamCard.vue
  front/src/store/index.js
Labels: Feature 🎉

#59 feat: use store for assignedTeamId v2
  front/src/components/TeamCard.vue
  front/src/store/index.js
  front/src/views/Logout.vue
Labels: Feature 🎉

#60 chore: secure database access
  firestore.rules
Labels: Technical task 👨🏻‍🔧

#63 Router guards v2 / Add schedule page
  front/src/assets/pages/gifs.png
  front/src/components/Drawer.vue
  front/src/firebase/config.json
  front/src/firebase/init.js
  front/src/main.js
  front/src/router/index.js
  front/src/views/Gifs.vue
  front/src/views/Login.vue
  front/src/views/Schedule.vue
Labels: Bug 🐜, Feature 🎉, Technical task 👨🏻‍🔧
