Repository ytvnr/gif-of-the-day, pull requests merged in 2020-01, with the labels that each got.

#33 chore: auto label PR
  .github/labels.yml
  .github/workflows/pull_request_labeler.yml
Labels: Technical task 👨🏻‍🔧

#31 docs: add pull request template and documentation 👨‍🏫
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: Documentation 📒

#30 feat: upgrade serialize js and vue plugins 👁
  front/package-lock.json
  front/package.json
Labels: Technical task 👨🏻‍🔧

#34 feat: init gif table
  front/src/components/TeamCard.vue
  front/src/router/index.js
  front/src/views/Gifs.vue
Labels: Feature 🎉

#39 feat: migrate to vuetify ✈️
  front/package-lock.json
  front/package.json
  front/public/index.html
  front/src/App.vue
  front/src/assets/logo.svg
  front/src/components/Drawer.vue
  front/src/components/Footer.vue
  front/src/main.js
  front/src/plugins/vuetify.js
  front/src/views/Gifs.vue
  front/vue.config.js
Labels: Feature 🎉, Nice to have 🦞, Technical task 👨🏻‍🔧, Work in progress 🚧
