Repository ytvnr/gif-of-the-day, pull requests merged in 2020-04, with the labels that each got.

#91 Feature / Some improvements
  front/.env
  front/src/components/Footer.vue
  front/src/firebase/config.json
  front/src/firebase/init.js
  front/src/services/github.service.js
  front/src/views/About.vue
  front/src/views/Gifs.vue
  front/src/views/Home.vue
  front/src/views/Register.vue
  front/src/views/Schedule.vue
Labels: Bug 🐜, Feature 🎉, Technical task 👨🏻‍🔧

#99 doc: Create LICENSE
  LICENSE
Labels: Documentation 📒

#100 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Documentation 📒

#98 doc: update readme and contributing
  CONTRIBUTING.md
  README.md
Labels: Documentation 📒

#96 fix: register with display name
  front/src/services/teams.service.js
  front/src/store/index.js
  front/src/views/Register.vue
Labels: Feature 🎉

#106 feat: redesign team card
  front/src/components/TeamCard.vue
Labels: Feature 🎉

#108 feat: use image load on gifs page
  front/.env
  front/src/firebase/init.js
  front/src/views/Gifs.vue
  front/src/views/Login.vue
  front/src/views/Register.vue
  front/src/views/Schedule.vue
Labels: Bug 🐜, Feature 🎉, Nice to have 🦞, Technical task 👨🏻‍🔧

#111 feat: no teams text
  front/src/views/Teams.vue
Labels: Feature 🎉, Nice to have 🦞

#110 feat: manage organization 👮‍♀️
  CONTRIBUTING.md
  firestore.rules
  front/src/App.vue
  front/src/components/Drawer.vue
  front/src/router/index.js
  front/src/services/organizations.service.js
  front/src/services/teams.service.js
  front/src/store/index.js
  front/src/views/ProfileNotAccepted.vue
  front/src/views/Teams.vue
Labels: Feature 🎉

#113 feat: display the chooser of a theme and fix date issue
  CONTRIBUTING.md
  front/src/services/teams.service.js
  front/src/views/Schedule.vue
Labels: Feature 🎉

#114 fix: allow theme choosing only if belonging to a team
  front/src/components/Drawer.vue
  front/src/router/index.js
  front/src/views/Home.vue
Labels: Bug 🐜

#115 fix: redirect to '/new/choose' issue template instead of '/new'
  front/src/components/Footer.vue
Labels: Bug 🐜

#117 fix: overlay when status is loading in store
  front/src/App.vue
  front/src/store/index.js
Labels: Bug 🐜

#116 fix: display home page random gif into a card
  front/src/views/Home.vue
Labels: Bug 🐜

#120 fix: change home tiles order and add link to FAQ
  front/src/views/Home.vue
Labels: Bug 🐜

#118 fix: schedule fixed column width
  front/src/views/Schedule.vue
Labels: Bug 🐜

#119 chore: use github secrets for deployment
  .github/workflows/on-push.yml
  front/.env
  front/.env.local
  front/.gitignore
  front/package.json
Labels: Technical task 👨🏻‍🔧, Work in progress 🚧

#122 fix: wording in action
  .github/workflows/on-push.yml
Labels: Bug 🐜

#123 feat: return from ouahid's test session
  front/src/components/Footer.vue
  front/src/components/NavBar.vue
  front/src/components/TeamCard.vue
  front/src/views/Faq.vue
  front/src/views/Gifs.vue
  front/src/views/Home.vue
  front/src/views/Login.vue
  front/src/views/Logout.vue
  front/src/views/ProfileNotAccepted.vue
  front/src/views/Register.vue
  front/src/views/Schedule.vue
  front/src/views/Teams.vue
Labels: Bug 🐜

#126 feat: god favicon
  front/public/favicon.ico
  front/public/img/icons/android-chrome-192x192.png
  front/public/img/icons/android-chrome-512x512.png
  front/public/img/icons/apple-touch-icon-120x120.png
  front/public/img/icons/apple-touch-icon-152x152.png
  front/public/img/icons/apple-touch-icon-180x180.png
  front/public/img/icons/apple-touch-icon-60x60.png
  front/public/img/icons/apple-touch-icon-76x76.png
  front/public/img/icons/apple-touch-icon.png
  front/public/img/icons/favicon-16x16.png
  front/public/img/icons/favicon-32x32.png
  front/public/img/icons/favicon.ico
  front/public/img/icons/msapplication-icon-144x144.png
  front/public/img/icons/mstile-150x150.png
  front/public/img/icons/safari-pinned-tab.svg
Labels: Feature 🎉

#125 fix: keep headers in schedule vue for extension mode
  .github/labels.yml
  front/src/views/Schedule.vue
Labels: Bug 🐜

#124 feat: display gif in full screen mode 🎉
  extension.zip
  extension/icon.png
  extension/icons/128.png
  extension/icons/152.png
  extension/icons/16.png
  extension/icons/192.png
  extension/icons/32.png
  extension/icons/48.png
  extension/icons/512.png
  extension/icons/favicon.ico
  extension/logo.png
  extension/manifest.json
  extension/release.zip
  front/src/App.vue
  front/src/components/FullScreenGif.vue
  front/src/components/ProfileNotAccepted.vue
  front/src/router/index.js
  front/src/views/Gifs.vue
  front/src/views/Home.vue
  front/src/views/ProfileNotAccepted.vue
Labels: Bug 🐜, Feature 🎉, Work in progress 🚧

#129 feat: add powered by giphy adn link to Giphy terms of service
  front/src/components/FullScreenGif.vue
  front/src/components/GiphyPowered.vue
  front/src/views/Gifs.vue
  front/src/views/Home.vue
Labels: Feature 🎉

#130 chore: clean router
  front/src/router/index.js
Labels: Technical task 👨🏻‍🔧

#136 fix: be enable to select date in the future
  front/src/views/Schedule.vue
Labels: Bug 🐜

#140 feat: week-end improvements 👌
  front/src/components/GiphyPowered.vue
  front/src/components/TeamCard.vue
  front/src/views/Home.vue
  front/src/views/Schedule.vue
  front/src/views/Teams.vue
Labels: Feature 🎉, Nice to have 🦞

#141 fix: be able to select date in the future
  front/src/views/Schedule.vue
Labels: Bug 🐜

#143 feat: copy gif url to clipboard
  front/src/components/FullScreenGif.vue
  front/src/components/RefreshButton.vue
  front/src/components/UrlCopier.vue
  front/src/views/Home.vue
Labels: Feature 🎉, deploy-to-staging 🚜
